- 
  gather_facts: false
  hosts: all
  name: "**Gathering Information about Hosts**"
  tasks: 
    - 
      win_user: ~
        name: Usertesting
        password: Ihatethis123
        state: present
      